# Generated by Django 2.2.5 on 2022-01-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verifiey',
            new_name='email_verified',
        ),
    ]
